import '@/styles/globals.css';
import 'react-toastify/dist/ReactToastify.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// Context Provider
import { Provider as ContextProvider } from '@/context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
