import '@/styles/globals.scss';
import 'react-toastify/dist/ReactToastify.css';

// Context Provider
import { Provider as ContextProvider } from '@/context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
